const FREE_YEARS_FOOTBALL = [2021, 2022, 2023]
const API_SOURCE_NAME = 'SPORTS_API'

const SCRAPER_MODULE = 'SCRAPER'
const IS_FREE_PLAN = (process.env.API_PLAN === 'FREE')

export { FREE_YEARS_FOOTBALL, API_SOURCE_NAME, SCRAPER_MODULE, IS_FREE_PLAN}